<a href="https://colab.research.google.com/github/Nawin03-DS/Python-Notes/blob/main/Naveen_python_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=10
b=20
print(a)

10


In [ ]:
print(a+b)

30


In [ ]:
a=b=c=10
print(a)

10


In [ ]:
print("Hello World")

Hello World


In [ ]:
print(5)
print(10)


5
10


In [ ]:
print(type(5))
print(type(10))


<class 'int'>
<class 'int'>


#28-03-2026


In [ ]:
a="Hello World"
print(a)
print(type(a))


Hello World
<class 'str'>


In [ ]:
a ="Hello World!"
#print the 'e' from the above string
#[index_position]
print(a[1])

e


In [ ]:
#print the range of character from the above--.'Hello'
#[string_index:end_index]
print(a[0:5])

Hello


In [ ]:
a ="Hello World!"
#print the even index position character.
#[strat:end:step]
print(a[0:12:2])

HloWrd


In [ ]:
print(a[0:12:2]) #odd index characters

HloWrd


In [ ]:
print(a[1:12:2])

el ol!


In [ ]:
print(a[11])
print(a[len(a)-1])

!
!


Negative Indexing

In [ ]:
a= "hello world"
print(a)
print(type[0::12])
print(a[0::12])
print(a[0:12:2])
print(a[0:12:1])
print(a[0:11:3])
print(a[0:11:4])
print(a[6])
print(a[len(a)-1])
print(a[len(a)-2])

hello world
type[slice(0, None, 12)]
h
hlowrd
hello world
hlwl
hor
w
d
l


In [ ]:
a="hello naveen"
print(a[-1])
print(a[-2])
print(a[-3])
print(a[1])
print(a[3])
print(a[7])
print(a[3:5])
print(a[len(a)-2])

n
e
e
e
l
a
lo
e


In [ ]:
a="hello nawin chandra"
print(len(a))
print(a[0:12:2])
print(a[-1])
print(a[len(a)-2])
print(a)

19
hlonwn
a
r
hello nawin chandra


29-03-2025

In [ ]:
#what is comment?
#for better understanding about codes we do comments?
#how many types of comments?
#two types of comments
#1.single line comment-->
#2.multiline comment-->
#what is an IDE?
#integrated development environment
#IDE's are defined as code excutor, or compilers or interpretors
#google colab

In [ ]:
#what is python?
#1.python is a most emerging general purpose programming language.
#2.python is a high level programming language
#3.python is a object oriented programming language
#4.python is a dynamically typed programming language
#5.python is a interpreted programming language
#what is general purpose programming language?
#apart from the python in data management and AI development we can also use it for general works
#ex:- ISRO scientist use python for physics calculation
     #convert word into pdf
     #tracking the stocks
#what is main purpose python language?
#the main purpose of python in data management and AI development
#due to more core library we are using web development and mobile app development
#what is High level programming language?
#a. is also human friendly programming language. --->code are not changing into binary forms
#we can read the code as a english language ---> code readiability--> low lines of code--> python,java
#how many level of programming language?
#there are 2 level of programming language
#1.Low- level programming language?
#a.low level language is also known as machine friendly programming language.
#b.each line of code changing into binary form 1s and 0s
#c.more line of codes--->c++,c,.net
#Q).what is object oriented programming language?
  CLASS-->OBJECT-->
 #a.identity,
 #b.properties/attributes
## c.IDE(integrated developing environment)
   #c1.google colab,pycharm,jupyter notebook,vscode.
#what is dynamically typed programming language?
#we need to mention the data type of variables
#python can automatically read the data type by itself
a=10
b="Hello"
#how many types of programming languages?
#there are 2 types
#statically types:-->we need to define the data type for the variables
      int[a]=10
      str[b]="Hello"
Q)what is a interpreted programming language?
#python can execute the code line by line the final lines of code can be taken into consideration
a=10
b=20
a=5
b=50
print(a+b)
#note:-python is a most emerging general purpose high level oblect oriented,dynamically typed and inetrpreted programming language.
#1.Numerical data types
#2.arthametic operators
#3.round0
#4.floor and cell values
#5.types of error
#6.variables


**01-04-2025**

In [ ]:
a = "pythonlife"
for i in a:
  print(i)

p
y
t
h
o
n
l
i
f
e


In [ ]:
#while True:
#  print("hello")

In [ ]:
#kiran=9
#while kiran<15:
#  print("hello",kiran)
 # kiran+=1

In [ ]:
#for i in range(0,10):
 #   for j in range(0,100:)
  #  print(i+j)

**03-04-2025**

**conditional statements**

In [ ]:
print(1==1)
print("hello" == "hello")
print("Hello" == "hello")

True
True
False


In [ ]:
#what is conditional statements?
#to build decision making codes weather to check a condition is satisfied or not
#By using"Comparision operators" is also known as ----> Relation operators
#Q.How many types of relational operators?
"""There are 6 types of comparision operators
   1.equals too---> ==
   2.not equal too---> !=
   3.less than or equals too ---->  <=
   4.greater than or equals too ---> >=
   5.greater than--->   >
   6.less than --->   <

In [ ]:
#what are all

In [ ]:
#write a program to print weather student is pass or fail based on given input
#marks>=45 ---->pass
#else print  "bettre luck next time"

marks = int(input('enter your marks: '))
#write a program to print weather student is pass or fail based on given input
#marks>=45 ---->pass
#else print  "bettre luck next time"

marks = int(input('enter your marks: '))
if marks>= 45:
  print(f"congratulations yuouhave recieved {marks} marks")
else:
    print(f"Bettre luck next time you have recieved {marks} marks")

In [ ]:
#when there is more than 2 conditions we use elif keyword
#Q.where we can use the elif keyword
#Between if and else.
#write a program to check weather the given number is "+ve" or "-ve" or "neutral"
num = int(input("enter the num: "))
if num>0:
  print("+ve")
#when there is more than 2 conditions we use elif keyword
#Q.where we can use the elif keyword
#Between if and else.
#write a program to check weather the given number is "+ve" or "-ve" or "neutral"
num = int(input("enter the num: "))
if num>0:
  print("+ve")
elif num ==0:
  print('nuetral')
else:
  print("-ve")
if num>0:
  print("+ve")
elif num ==0:
  print('nuetral')
else:
  print("-ve")

In [ ]:
#q. if i want to check multiple conditions at a time what i have to do?
#we need to use the "logical operators"
#there are 3 types

1.NOT

In [ ]:
#it reverse you actual output
print(1==1)
print(not(1==1))

2.And
-->if all the conditions are true then it execute the program

In [ ]:
a=45
b=30
c=15
d=60
#check that a is greater than c and b is greater than c and d is greater than a
#if all the conditions are true print that all true else print not satisfied
if a>c and b>c and d>a:
  print('all are true')
else:
  print(not satisfied)

all are true


OR---> if any one condition is true it executes the program

In [ ]:

if a>c and b<c and d<a:
  print('all are true')
else:
  print('Not satisfied')

Not satisfied


In [ ]:
#can i use the and , or operator at a time--> yes
a=155
b=60
c=180
d=90
if a>b and c>d or d<b or b<c and a>d:
  print('all are true')
else:
  print('False')

all are true


**Nested conditions**

In [ ]:
#what is nested condition?
#writing a condition inside the another condition is known as nested condition
#what is the purpose of nested condition?
#A program or a step can be executed if the previous condition is satisfied
#if we want a series of output then we can use nested conditions

In [ ]:
a=25
#check the above number is greater than 10,20,30,40,50
#if it is greater than 10-----> a is greater than 10
#if it is greater than 20-----> a is greater than 20
#if it is greater than 30-----> a is greater than 30
#if it is greater than 40-----> a is greater than 40
if a>40:
  print('a is greater than 10')
  if a>20:
    print('a is greater than 20')
    if a>30:
      print('a is greater than 30')
      if a>40:
        print('a is greater than 40')

      else:
        print("a is less than 10")
    else:
     print("a is less than 20")
  else:
   print("a is less than 30")
else:
  print("a is less than 40")

a is less than 40


In [ ]:
if a>40:
  print('a is greater than 10')
  if a>20:
    print('a is greater than 20')
    if a>30:
      pass

In [ ]:
#write a program to print grades of students based on marks along with grades print marks
#if marks between 50 to 60--> 'D' along with marks
#if marks between 61 to 70---> 'C' along with marks
#if marks between 71 to 80---> 'B' along with marks
#if marks between 81 to 90---> 'A' along with marks
#if marks between 91 to 100---> 'A+' along with marks
#if marks below 50 print---> Better luck next time---> along with marks
#if marks more than 100--->"print(don't be smart)"

***04-04-2025***

In [ ]:
print("Mom" == "mom")

False


**loops**

In [ ]:
 print(1<=5)
 print(2<=5)
 print(6<=5)

True
True
False


In [ ]:
 #write a program to run a lift if the user given a input() stop the lift at particular floor?
 user_input=int(input('enter the floor number'))
 initial = 1
 while initial <= user_input:
  print(f'you are at{initial} floor')
  initial = initial + 1


In [ ]:
word="malayalam"
if word==word[::-1]:
  print("the word is palindrome")
else:
  print("its not a palindrome")

the word is palindrome


In [ ]:
num =int(input("enter a number:"))
target=7
while num<target:
  if num == 0:
   print("the first 3 multiples of the given number is: ",num)
  num = num + 1

In [ ]:
num =int(input("enter a number:"))
target=int(input("enter the range of multiple number:"))
target=10
while num<target:
  if num == 0:
   print("the first 3 multiples of the given number is: ",num)
  num = num + 1

In [ ]:
age=int(input("enter your age"))
if age>=18:
  print("You are old enough to drive")
else:
  print(f"You need {18-age} more years to learn to drive")

## **07-04-2025**

In [ ]:
print("Hello World!")


Hello World!


**Numerical Data Type**

In [ ]:
#there are 3 types of numerical data types
#1. integer---> A whole number either +ve or -ve without decimal point is known as a integer
print(20)
print(15)
print(type(10))


20
15
<class 'int'>


In [ ]:
#2.float--> A whole number either +ve or -ve with decimal point is known as float
print(-3.5)
print(type(-3.5))

-3.5
<class 'float'>


In [ ]:
#3.complex number--> A real number with its imaginary part is known as complex number
print(2+5j)
print(type(2+5j))

(2+5j)
<class 'complex'>


In [ ]:
print(type(5j))

<class 'complex'>


**Arthametic operators**

In [ ]:
#there are 7 types of arthametic operators
#1.Addition--> +
print(10+5)
print(type(10+5))
print(10-5)
print(type(10-5))
print(20*5)
print(type(20*5))
print(20/10)
print(type(20/10))

15
<class 'int'>
5
<class 'int'>
100
<class 'int'>
2.0
<class 'float'>


In [ ]:
#modulus--> % ---> remainder of the division is known as modulus
#to find even and odd index or data we use modulus
print(20%10)
print(type(20%10))

0
<class 'int'>


In [ ]:
#floor division--> // --> it ignores the values after the decimal point
print(10//3)
print(10/3)
#floor division is also known as integer division

3
3.3333333333333335


**floor and ceil value**

In [ ]:
#what is a floor value?
#In a decimal number the values before the decimal point is known as floor value
#what is ceil value?
#for a decimal number the next upcoming value is known as ceil value
#to get the floor and ceil value we need to use rond()
print(round(9))
print(round(9.4))
print(round(9.5))

9
9
10


In [ ]:
print(123.8743527866)
print(round(123.8743527866,2))
print(round(123.8743527866,-1))
print(round(125.8743527866,-1))


123.8743527866
123.87
120.0
130.0


In [ ]:
print(round(1234.876475676,2))
print(round(186.89658768,4))
print(round(130875.09898709269319,-5))
print(round(8754.96754,4))

1234.88
186.8966
100000.0
8754.9475


**08-04-2025**

**variables**

In [ ]:
# a variable is a container were we can store or valuable information and we reuse it
#how can we create a variable?
##to create a variable we use some industrial rules and alphabets?


In [ ]:
x = 40
son = x/2
print(son)

20.0


**types of error**

In [ ]:
#there are two types errors
#1. syntax error
#2. logical error

In [ ]:
#what is syntax error?
#breaking the rules of programming language will rise an syntax error
""" Hello
    Good Day! """
print("Hello world")

Hello world


**09-04-2025**

#collections

In [ ]:
#in collection there are two types of data
#1.Heterogeneous data:- if the collection is having different data types inside it we called it as heterogeneous data
#ex: a list is having int, float, string
#2.Homogeneous data:-if the collection is having single data type is known as Homogeneous data

In [ ]:
#what is collectiom and how many types of basic data structures do we have?
#there are four types of collections ( is also known as iterables)
"""1. list
   2. tuple
   3. set
   4. dictionary"""

# list

In [ ]:
#what is list? and define a list or how to declare list?
#list can be declared in ---[]
#list is ordered, mutable(changable), and list allows the duplicate data

# list allows the duplicate data

In [ ]:
l1 = ['apple','banana','mango','orange','apple','banana','grapes']
print(len(l1))
print(l1)
print(type(l1))
print(type(11))

7
['apple', 'banana', 'mango', 'orange', 'apple', 'banana', 'grapes']
<class 'list'>
<class 'int'>


# list is ordered

items in the list is having a sequence of index position numbers

In [ ]:
l1 = ['apple','banana','mango','orange','apple','banana','grapes']
#in above list 12 print only 'orange'
print(l1[3])
#[strat:end]
#print the last characters from 'mango to banana'
print(l1[2:6])
#print the even position
print(l1[::2])
#print the odd position
print(l1[1::2])


orange
['mango', 'orange', 'apple', 'banana']
['apple', 'mango', 'apple', 'grapes']
['banana', 'orange', 'banana']


In [ ]:
#negative indexing start from -1
#accesing the characters in the reverse direction
#print the last character in the reverse direction
#[start:end:step]
print(l1[-1:-8:-1])

['grapes', 'banana', 'apple', 'orange', 'mango', 'banana', 'apple']


In [ ]:
#default indexing--> [start(0):end(len(list)):step(1)]
print(l1[::-1])

['grapes', 'banana', 'apple', 'orange', 'mango', 'banana', 'apple']


In [ ]:
#LIST IS MUTABLE
#if a data structure is mjtable means--> it has follow 3 properties
1.swap or replace the items in existing list
2.add new items to the existing list
3.remove th eitems from existing list

1.swap or replace the items in existing list

In [ ]:
l3 = ['python','java','js','reactjs','.net','c','c++']
#replace the'js' with 'java-script'===> by using index position number we place the items
l3[2] = 'javascript'
print(l3)
#replace the range of characters from java to 'reactjs'
l3[1:4] = 'pandas','numpy','seaborn'
print(l3)



['python', 'java', 'javascript', 'reactjs', '.net', 'c', 'c++']
['python', 'pandas', 'numpy', 'seaborn', '.net', 'c', 'c++']


add new items to the existing list

In [ ]:
#to add new items to the existing we are having some methods
l4 = ['python', 'pandas', 'numpy', 'seaborn', '.net', 'c', 'c++']
print(dir(l4))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
#1.append() by the defualt it add the item at the end index podsition number
#at a time we can add only 1 num
l4.append('java')
print(l4)

['python', 'pandas', 'numpy', 'seaborn', '.net', 'c', 'c++', 'java']


In [ ]:
#2.insert(index,'item):- used to add the item at particular index position
#2.insert(index,'item):- used to add the item at particular index position
#we cannot able to insert the multiple items at a time by using the insert method
#Q. add the 'statistics' at the 5th index position

l4.insert(5,'statistics')
print(l4)

['python', 'pandas', 'numpy', 'seaborn', '.net', 'statistics', 'c', 'c++', 'java']


In [ ]:
#3.extend():- add the multiple items from other collections
#by default those data can be add at last index position
l5 = [1,2,3,4,5,6]
l6 = [7,8,9,10,11,12]
print(l6+l5)

[7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6]


In [ ]:
#extend the 15 with 16
l5.extend(l6)
print(l5)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


# 10-04-2025

set


In [ ]:
s1={'apple','banana','mango','orange','apple','banana','grapes'}
print(s1)
print(len(s1))
print(type(s1))



{'grapes', 'banana', 'mango', 'apple', 'orange'}
5
<class 'set'>


set is unorderd


In [ ]:
#the data points in the set doesnot have index position
print(s1[1])
#'set' object is not subscriptable beacuse data in the set doesnot have index position

In [ ]:
l = ['grapes', 'banana', 'mango', 'apple', 'orange']
print(l)

['grapes', 'banana', 'mango', 'apple', 'orange']


In [ ]:
s2 = {'grapes', 'banana', 'mango', 'apple', 'orange'}
print(s2)

{'grapes', 'banana', 'mango', 'apple', 'orange'}


set is immutable
--> in set we can add and remove the items but we cannot replace the items

In [ ]:
s3 = {'grapes', 'banana', 'mango', 'apple', 'orange'}
print(dir(s3))
"""'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update'"""

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [ ]:
#how can add the items in the set?
#1.add() at a time we can add only single item
#so the item can be stored at any where
#add watermelon to the s3
s3.add('watermelon')
print(s3)

{'grapes', 'banana', 'mango', 'apple', 'orange', 'watermelon'}


In [ ]:
#2.update() by using update method we can add multiple items to the set
s4 = {1,2,3,4,5,6,7,8,9,10}
s3.update(s4)
print(s3)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'mango', 'orange', 'watermelon', 'banana', 'apple', 'grapes'}


remove items from the set

In [ ]:
s5 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'apple', 'banana', 'grapes', 'mango', 'orange', 'watermelon'}
#pop() is bad practice beacuse it doesnt have ondex position
s5.pop()
print(s5)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 'mango', 'orange', 'watermelon', 'banana', 'apple', 'grapes'}


In [ ]:
#remove('item_name')
s5.remove('mango')
print(s5)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 'orange', 'watermelon', 'banana', 'apple', 'grapes'}


In [ ]:
#discard('item_name'):- used to remove the items from the sets
s5.discard(8)
print(s5)

{2, 3, 4, 5, 6, 7, 9, 10, 'orange', 'watermelon', 'banana', 'apple', 'grapes'}


In [ ]:
#what is the difference between the remove and discard?
s5.remove('mango')
print(s5)

In [ ]:
s5.discard('mango')
print(s5)

{2, 3, 4, 5, 6, 7, 9, 10, 'orange', 'watermelon', 'banana', 'apple', 'grapes'}


In [ ]:
#in remove method if the item exist it wont rise error else if the item not present in the set it will rise error
#where as in the discard if the item exist or not esxist it wint rise the error

In [ ]:
#clear():- it returns empty set
s5.clear()
print(s5)

set()


In [ ]:
#sets are faster the than the list and tuples beacuse sets are ordered and immutable

In [ ]:
s6 = {'a','b','c','d'}
s7 = {'d','e','f','g'}
print(s6.union(s7))

{'b', 'd', 'e', 'a', 'c', 'g', 'f'}


In [ ]:
#i want the common data from the data set
print(s6.intersection(s7))

{'d'}


In [ ]:
print(s6.difference(s7))

{'b', 'a', 'c'}


# dictionary

In [ ]:
#what is dictionary or define dictionary or how can we declare a dictionary?
#dictionary acn be declare by using--> {}
#how can we store the data in dictionary
#{key:value} pairs

In [ ]:
#dictionary is defined as unordered,mutable, and dict won't allow duplicate data

dict won't allow duplicate data

In [ ]:
d1 = {
    'Name' : 'Naveen',
    'Age' : 24,
    'Occupation' : 'Data Scientist',
    'Education' : 'MS',
    'Education' : 'Masters'
}
print(d1)
print(len(d1))


{'Name': 'Naveen', 'Age': 24, 'Occupation': 'Data Scientist', 'Education': 'Masters'}
4


# dict is unordered

In [ ]:
d1 = {
    'Name' : 'Naveen',
    'Age' : 24,
    'Occupation' : 'Data Scientist',
    'Education' : 'MS',
}
#print(d1[1])
#how can we access the data from dict
print(d1['Education'])


MS


In [ ]:
#access the specific keys
print(d1['Name','Age'])

In [ ]:
k = ['Name','Age','Occupation','Education']
print(k)
print(d1['Name'],d1['Age'],d1['Occupation'],d1['Education'']

In [ ]:
#replace the items in the dict
d1 = {
    'Name' : 'Naveen',
    'Age' : 24,
    'Occupation' : 'Data Scientist',
    'Education' : 'MS',
}
d1['Name'] = 'Naveen Jatoth'
print(d1)

{'Name': 'Naveen Jatoth', 'Age': 24, 'Occupation': 'Data Scientist', 'Education': 'MS'}


In [ ]:
#add the new key:value pair to the d1
d1['Bike'] = 'Nani'
print(d1)

{'Name': 'Naveen Jatoth', 'Age': 24, 'Occupation': 'Data Scientist', 'Education': 'MS', 'Bike': 'Nani'}


In [ ]:
#remove the data from dict
print(dir(d1))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [ ]:
#pop('key_name'):- we must and should have give the keynames
d1.pop('Education')
print(d1)

{'Name': 'Naveen Jatoth', 'Age': 24, 'Occupation': 'Data Scientist', 'Bike': 'Nani'}


In [ ]:
 #popitem():- it removes the key value pairs as a tuples
d1.popitem()

('Occupation', 'Data Scientist')

In [ ]:
#clear()
d1.clear()
print(d1)

{}


In [ ]:
d1 = {
    'Name' : 'Naveen',
    'Age' : 24,
    'Occupation' : 'Data Scientist',
    'Education' : 'MS',
    'Fruits' : ['apple','banana','mango','orange']
}
#print 'mango' from above d1
print(d1['Fruits'][2])


mango


In [ ]:
#replace the orange with grapes
d1['Fruits'] [-1] = 'grapes'
print(d1)

{'Name': 'Naveen', 'Age': 24, 'Occupation': 'Data Scientist', 'Education': 'MS', 'Fruits': ['apple', 'banana', 'mango', 'grapes']}


In [ ]:
#update()
d2 = {'nani':'chay'}
d1.update(d2)
print(d1)

{'Name': 'Naveen', 'Age': 24, 'Occupation': 'Data Scientist', 'Education': 'MS', 'Fruits': ['apple', 'banana', 'mango', 'grapes'], 'nani': 'chay'}


In [ ]:
print(d1.keys())
print(d1.values())
print(d1.items())

dict_keys(['Name', 'Age', 'Occupation', 'Education', 'Fruits', 'nani'])
dict_values(['Naveen', 24, 'Data Scientist', 'MS', ['apple', 'banana', 'mango', 'grapes'], 'chay'])
dict_items([('Name', 'Naveen'), ('Age', 24), ('Occupation', 'Data Scientist'), ('Education', 'MS'), ('Fruits', ['apple', 'banana', 'mango', 'grapes']), ('nani', 'chay')])


In [ ]:
"""1.list --> []---> ordered,mutable,allows duplicates
                --->adding methods:- append(),insert(),extend()
                ---.removing methods:-pop(),remove(),clear()
  2.tuples  -->()--->ordered,immutable,allows duplicates
                --->we cannot replace or add or remove items
  3.sets  -->  unordered,immutable, doesnot allows duplicates
               adding methods--:- add,update,union
               removing method:-pop(), remlove(),discard(),clear(),intersection(),difference()

 4.dictionary:- {key:values} pairs---> unordered,mutable,wont allow duplicates
              adding methods-->update()
              -->dict_name['new_key_names] = 'value'
              remove method  -:pop(),clear(),popitem()"""

**Assessment** 11-04-2025

In [ ]:
#What is the output of the following list operation
aList = [10, 20, 30, 40, 50, 60, 70, 80]

print(aList[2:5])
print(aList[:4])


[30, 40, 50]
[10, 20, 30, 40]


In [ ]:
#What is the output of the following list assignment
aList = [4, 8, 12, 16]
aList[1:4] = [20, 24, 28]
print(aList)

[4, 20, 24, 28]


In [ ]:
#Select all the correct options to copy a list
aList = ['a', 'b', 'c', 'd']
print

In [ ]:
#What is the output of the following
aList = [5, 10, 15, 25]
print(aList[::-2])

[25, 10]


In [ ]:
#What is the output of the following code
aSet = {1, 'PYnative', ('abc', 'xyz'), True}
print(aSet)

{('abc', 'xyz'), 1, 'PYnative'}


In [ ]:
#What is the output of the following
sampleSet = {"Yellow", "Orange", "Black"}
sampleSet.discard("Blue")
print(sampleSet)

{'Yellow', 'Black', 'Orange'}


In [ ]:
#What is the output of the following union operation

set1 = {10, 20, 30, 40}
set2 = {50, 20, "10", 60}
set3 = set1.union(set2)
print(set3)

{'10', 40, 10, 50, 20, 60, 30}


In [ ]:
#What is the output of the following set operation
sampleSet = {"Yellow", "Orange", "Black"}
sampleSet.update(["Blue", "Green", "Red"])
print(sampleSet)

{'Yellow', 'Black', 'Blue', 'Red', 'Green', 'Orange'}


In [ ]:
#What is the output of the following set operation
set1 = {"Yellow", "Orange", "Black"}
set2 = {"Orange", "Blue", "Pink"}
set3 = set2.difference(set1)
print(set3)

{'Blue', 'Pink'}


In [ ]:
#What is the output of the following
sampleSet = {"Yellow", "Orange", "Black"}
sampleSet.add("Blue")
sampleSet.add("Orange")
print(sampleSet)

{'Blue', 'Yellow', 'Black', 'Orange'}


In [ ]:
#What is the output of the following

set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 10, 30, 40, 80, 20, 50}
print(set1.issubset(set2))
print(set2.issuperset(set1))

True
True


In [ ]:
#Given the following code, what will be the output?
a = [1, 2, 3]
b = a[:]
a[0] = 0
print(b)

[1, 2, 3]


In [ ]:
#What is the output of the following code?

from collections import deque
d = deque([1, 2, 3])
d.appendleft(0)
d.pop()
print(d)

deque([0, 1, 2])


In [ ]:
#What will be the output of the following code?
x = 5
if x > 10:
    print("Greater")
elif x == 5:
    print("Equal")
else:
    print("Smaller")

Equal


In [ ]:
Set = {30, 40, 50}
Set.update([10, 20, 30])
print(Set)
#Predict the output:(ignore the order of numbers as set is unordered)


{40, 10, 50, 20, 30}


In [ ]:
Tuple = (3e-04, False, True, 8.12, 1.111, True)
value = 0
for z in Tuple:
    value += int(z)
print(value)

#Predict the output of the python code:

11


In [ ]:
st = 'Happy Christmas and Happy new year'

if st.startswith("Happy"):
    x = st.rsplit("Happy")  # Split by "Happy"

print(len(x))
#What is the output of above code?

3


In [ ]:
#What is the output of the above code?
print(ord('a'))


97


In [ ]:
#What will be the output of this code?
print(round(2.4999, 0))

2.0


In [ ]:
#What will be the output of the following code?
s = "Python"
print(s[1:4:2])

yh


In [ ]:
#Study the following statements:
>>> str1 = "javat"
>>> str2 = ":"
>>> str3 = "point"
>>> str1[-1:]
#What will be the output of this statement?


't'

In [ ]:
#Study the following program:
#Study the following program:
a = 1
while True:
      if a % 7 == 0:
         break
      a += 1
print(a)
#Which of the following is correct output of this program?



7


In [ ]:
#Study the following program:
a = 1
while True:
      if a % 7 = = 0:
         break
print(a)
a += 1

#Which of the following is correct output of this program?



SyntaxError: invalid syntax (<ipython-input-34-b5faa2174a33>, line 4)

In [ ]:
z = "xyz"
j = "j"
while j in z:
  print(j, end=" ") # Indented the print statement within the while loop

In [ ]:
#Study the following program:
d = {0: 'a', 1: 'b', 2: 'c'}
  for i in d:
print(i)
#What will be the output of this statement?

IndentationError: unexpected indent (<ipython-input-39-8899d81c26a7>, line 3)

In [ ]:
#What will be the output of the following Python code snippet?

my_tuple = ('a', 'b', 'c', 'd', 'e')
print(my_tuple.index('c'))

2


In [ ]:
#What will be the output of the following Python code snippet?
my_tuple = ('a', 'b', 'c', 'a', 'b', 'a')
print(my_tuple.count('a'))

3


In [ ]:
#What will be the output of the following Python code snippet?
my_tuple = (1, 2, 3)
result = my_tuple + (4,)
print(result)

(1, 2, 3, 4)


# 14-04-2025

In [ ]:
print('Hello world!')
#what is a function?
#Function isa block of code which can be executed when we call it

Hello world!


In [ ]:
#How can we create a function?
#By using the 'def' keyword
def welcome():
  print("Hello welcome to Python session")
#How can we call the function
welcome()

Hello welcome to Python session


In [ ]:
#How can we create a function?
#By using the 'def' keyword
def welcome():
  print("Hello welcome to Python session")
#How can we call the function
welcome()

Hello welcome to Python session


In [ ]:
#write a function to print the hello world?
def f1():
  print("Hello world!")
#call the function
f1()

Hello world!


In [ ]:
#what is the main purpose of the functions?
#to avoid duplicate code and encourages to write DRY Codes

Parameters and aruguments

In [ ]:
#what is parameter?
#when we define a function we create a variable which is known as parameter
def welcome(name):
  print(f'Hello {name} welcome to python session')
#call the function
welcome('Guys')
#what is an argument?
#when we call a function we pass some values which are known as arguments

Hello Guys welcome to python session


In [ ]:
#How many parameters and argument do i need to pass
#A)No of parameters == No of arguments
def details(name,age,gender,contact):
  print(f"Hello please check your details, name: {name},age: {age},Gender: {gender},cell:{contact}")
#call the function details
details('shahul',29,'M',982398743)

Hello please check your details, name: shahul,age: 29,Gender: M,cell:982398743


In [ ]:
#I dont how many parameters i need to pass then what i have to do?
def details(**name):
  print(name)
details(name='shahul',Age=29,gender='M',Occupation='DS',Education='masters')

{'name': 'shahul', 'Age': 29, 'gender': 'M', 'Occupation': 'DS', 'Education': 'masters'}


In [ ]:
#I dont know how many argument i need to pass? then what we need to do?
def program(*name):
  print(name)
program('python','js','java','.nedt')

('python', 'js', 'java', '.nedt')


In [ ]:
"""1.**:- KWARGS-->kEYWORD Arbitrary Arguments
       -->when we dont know how many parameters we need to pass  we use KWARGS
       --> The default data type for KWARGS are Dictionary
   2. *:- ARGS--> Arbitrary argumenmts
          --> when we dont know how many argument we need to pass we use args
          -->The default data type for args is "Tuple"    """

In [ ]:
from re import I
l1 = [1,2,3,4,5,6,7,8,9,10]  #55
sum = 0
#write a program to print sum of numbers in the above list
for i in l1:
  sum = sum + i
print(sum)

55


In [ ]:
l = [10,20,30,40,50,60,70,80,90]
def sum(n):
  sum = 0
  for i in n:
    sum = sum+i
  print(sum)
#call the function
sum(l)

450


In [ ]:
l2 = [83838737,8387373,37363262]
sum(l2)

129589372


In [ ]:
t = (1,2,3,4,5,6)
sum(t)

21


In [ ]:
l = [3,5,6,7,8,98,97,65,43,42]
def find_eve(n):
  for i in n:
    if i % 2 == 0:
      print(i)
find_eve(l)

6
8
98
42


In [ ]:
t = (1,2,3,4,5,6,7,8,9)
find_eve(t)

return--> is similar to print()

--> it return back the values to the caller

In [ ]:
l = [3,5,6,7,8,98,97,65,43,42]
new = []
def find_eve(n):
  for i in n:
    if i %2 == 0:
      new.append(i)
  return(new)
find_eve(l)

In [ ]:
def f1(n1,n2):
  return n1+n2
print(f1(10,20))

30


In [ ]:
#what is afunction?
#how can we create a function?
#How can we call a function?
#what is parameters?
#what is arguments?
#what is kwargs?
#what is ARGS?
#what is return keyword?

In [ ]:
l = [1,-2,4,5,6,-9,-7,4,3,-2]
def check_sign(num):
  for i in num:
    if i>0:
      print('+ve')
    else:
      print('-ve')
check_sign(l)

+ve
-ve
+ve
+ve
+ve
-ve
-ve
+ve
+ve
-ve


In [ ]:
#write a function to print fibonacci series?

In [ ]:
def details(name,age,gender,contact):
  print(f"Hello please check your details, name: {name},age: {age},Gender: {gender},cell:{contact}")
#call the function details
details('shahul',29,'M',982398743)

Hello please check your details, name: shahul,age: 29,Gender: M,cell:982398743


In [ ]:
details(29,'shah',9487476,'M')

Hello please check your details, name: 29,age: shah,Gender: 9487476,cell:M


# 15-04-2025

In [ ]:
jupyter %notebook

In [ ]:
! pip


Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper c

In [ ]:
! pip install jupyter

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 85.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 26.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 57.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.6 MB/s eta 0:00:00
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 6.1.12
    Uninstalling jupyter-client-6.1.12:
      Successfully uninstalled jupyter-client-6.1.12
  Attempting uninstall: jupyter-server
    Found existing installation: jupyter-server 1.16.0
    Uninstalling jupyter-server-1.16.0:
      Successfully uninstalled jupyter-server-1.16.0


In [ ]:
! pip install numpy

In [ ]:
! pip install numpy

In [ ]:
#import numpy
import numpy as np

In [ ]:
#check the version of numpy
np.__version__

'2.0.2'

In [ ]:
#what is the difference between a list and numpy array
"""array: array can take homogeneous data
          array's are faster than the listbecause array's are immutable
          array's are having fixed memory"""

In [ ]:
#array's are ordered,immutable and also it allows the duplicate data
central object in numpy is Numpy Array's


In [ ]:
l = [1,2,3,4]
import numpy as np
a = np.array(l)
print(a)

[1 2 3 4]


In [ ]:
print(a[2])

3


In [ ]:
print(a[1:3])

[2 3]


In [ ]:
b = np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([1,2,3,4])
#i want to know the shape of the array
b.shape
#i want to know the element data type
b.dtype
#i want to know the dimension of my array
b.ndim
#i want to know the total number of elements in my array
b.size
#i want to know the size in byte of each element
b.itemsize


8

# 17-04-2025

In [ ]:
#HOW APPLY CONDITIONS IN THE ARRAY?
#np.where(condition,true,false)
import numpy as np

In [ ]:
a = np.array([1,2,3],[6,7,8],[1,4,4])
print(a)

In [ ]:
import numpy as np # Add this line to import the NumPy library

a = np.array(([1,2,3],[6,7,8],[1,4,4]))
# Changed list into a nested list to prevent the error "ValueError: only scalar arrays can be converted to a scalar index"
print(a)
#print the values greater than 2
b = np.where(a>2,True,False)
b = np.where(a>2,a,"No")
print(b)

[[1 2 3]
 [6 7 8]
 [1 4 4]]
[['No' 'No' '3']
 ['6' '7' '8']
 ['No' '4' '4']]


In [ ]:
#np.argwhere()
#compte the argument where the condition is true?
c = np.argwhere(a>2)
print(c)
print(a)

[[0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 1]
 [2 2]]
[[1 2 3]
 [6 7 8]
 [1 4 4]]


In [ ]:
a = np.array([10,19,20,30,41,50,61])
#compute the indexes where the numbers are divisible with 2
eve = np.argwhere(a%2==0).flatten()
print(eve)
a_even = a[eve]
print(a_even)


[0 2 3 5]
[10 20 30 50]


In [ ]:
#reshaping of the array's
#create a range of array up to 10
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#create a range of array 1 to 10
b = np.arange(1,11)
print(b)
#reshape the above array into 5 rows and 2 column
c = b.reshape(5,2)   #np.reshape(row,col)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#generate a range of array from 1 to 6 and reshape it into 2 rows and 3 column
d = np.arange(1,7)
print(d)
e = d.reshape(2,3)
print(e)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#NEWaxis:- it is used to create a new axis in the data
a = np.arange(1,7)
print(a.shape)

(6,)


In [ ]:
b = a[np.newaxis,:]
print(b)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
c = a[:,np.newaxis]
print(c)
print(c.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [ ]:
d = np.array([[1,2],[3,4],[5,6]])
print(d.shape)
e = d[np.newaxis,:]
print(e)
print(e.shape)

(3, 2)
[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)


In [ ]:
c = a[:,np.newaxis]
print(c.shape)

(6, 1)


In [ ]:
#concatenation:-
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#combine or concat above 2 arrays
c = np.concatenate((a,b.T), axis = 1)
print(c)

[[1 2 5]
 [3 4 6]]


In [ ]:
#HSTACK:- stack of array in sequence horizontally(column-level)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#VSTACK:- stack of array in sequence vertically(row-level)
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#COPYING:-
a = np.array([1,2,3])
b = a
b[0] = 42
print(a)

[42  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 42
print(a)
print(b)
#np.copy() is used when we make changes in the array it wont impact on the old array

[1 2 3]
[42  2  3]


In [ ]:
#Generating Array's
#generate an array of zeros with 2 rows and 3 column
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#generate an array of zeros with 3 rows and 3 column
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#generate an array of specific rows and column with specific values
c = np.full((3,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#generate an identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#generate an identity matrix
e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#generate a range of numbers upto 9
f = np.arange(10)
print(f)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace:- split the data into n equal parts
g = np.linspace(0,10,6)
#linspace(start,end,partitions)
print(g)

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
#RANDOM NUMBERS
#generate the random numbers that are uniformly distributed from 0-1
a = np.random.random((3,2))
print(a)

[[0.1500996  0.9947045 ]
 [0.25142166 0.7087134 ]
 [0.97744888 0.03170313]]


In [ ]:
#generate an array which is normally distributed or gussian distribution
#normally distribution  means ---> mean is zero and varianvce is 1
h = np.random.random(3,2)
print(h)
print(h.mean(),h.var(),h.std())

In [ ]:
#generate an array which is normally distributed or gussian distribution
#normally distribution  means ---> mean is zero and varianvce is 1
#To prevent the error, update the syntax to create a 3x4 array:
h = np.random.random((3,2))
#added extra parentheses to create an array of the desired shape
print(h)
print(h.mean(),h.var(),h.std())

[[0.24351441 0.28620605]
 [0.04250805 0.95445289]
 [0.47064707 0.81392794]]
0.4685427352422929 0.10346566810510181 0.3216607966555791


In [ ]:
#generate random integers from 10 to 20
i = np.random.randint(10,20,size=(10))
print(i)

[13 12 14 13 14 10 13 16 13 15]


In [ ]:
#generate an random interges upto 6 and divide it into size of 10
j = np.random.choice(7,size = (10))
print(j)

[1 4 4 5 3 6 6 0 2 6]


In [ ]:
from collections.abc import Sized
#how to check the numpy array or explore the numpy array?
"""1.np.shape
   2.np.Size
   3.np.dtype
   4.np.dim
   5.np.itemsize"""
#what is 1D,2D,3D array's?
#what is the difference between list and array?
#slicing operation with 1D and 2D?
#np.dot():- the arrays has to be in same length and dimensions
#np.diag()
#np.T
#np.linalg.inv()
#np.where(condition,true,false)
#np.argwhere(condition)
#np.concatenate():- we should match rows of two arrays
#np.reshape(rows,column)
#np.newaxis
#np.copy()
#np.hstack()
#np.vstack()
#np.faltten:- print the output in single line
#np.random.random((row,col)) --->uniform distribution
#np.random.randn(row,col)    -->normal distribution
#np.random.ranint(start,end,size=)
#np.random.choice(end,size)
#np.rray()
#np.arange()
#np.linspace(start,end,partitions)  --> divide the array into new axis
#np.one,np.zeros,np.full,

**30-04-2025**

In [ ]:
#STATS MODULE 2
What is hypothesis?
it is a priliminary assumption of data without analysis of the data

HO --> CORRECT
H1 ---> NOT CORRECT

H1 -->CORRECT
H1 -->NOT CORRECT

1. Null Hypothesis
2. Alternate Hypothesis

EX: if the x = 500 ml
  H1: x != 500 ml
  H0: x = 500 ml
  LEFT TAIL TEST

  EX: if the x < 500 ml
  H1: x != 500 ml
  H0: x = 500 ml
  RIGHT TAIL TEST

  we use two test to find the hypothesis
  1. Z-test
  2. T-test
  Z score-test:- the sample size is greater than 30
  T score-test:- the sample size is less than 30

  Z score-test formula
   Z = X-u\sigma\under root n

   x ->sample mean
   u ->population mean
   sigma ->population std
   n ->sample size

   a sample size of 400 was drawn and sample mean has found to be 99 test weather sample would have come from normal population which 100 and SD is 5% level of significance
   n = 400
   x = 99
   u = 100
   sigma = 8

   Z = -2.5

   L = 5%
   Zt SCORE = .OO539
   |Z| MODULUS = 2.5

   IF |Z| if greater then z alpha then reject the null hypothesis and accept the alternate hypothesis
   IF |Z| if less then z alpha then accept the null hypothesis and reject the alternate hypothesis

   H0 and H1 are always opposite
   Accept H1 alternate hypothesis

   H0 ->correct
      ->incorrect

   H1 ->correct
      ->incorrect

  when H0 is incorrect like company is selling less than 500 mml of milk but till then,untill or unless we are accepting it -->such a type of errors is known as TYPE-1 error
  when H0 is accepted when H1 is true --> such a type of errors is known as TYPE-I error
       H0 is accepted when H1 is true --> such a type of errors is known as TYPE-II error
  when H1 is incorrect like company is selling more than 500 mml of milk but till then,untill or unless we are accepting it -->such a type of errors is known as TYPE-2 error

  a medicine is tested on a particular person
  let H0:-medicine is curing deases
  correct: we say no medicine is not curing the disease
  what type of error it is?
  TYPE I error

  delhi govt claims ppm in air less than 70%
  find the type I and type II error
  H0 is correct: but our analysis says more then 70 -->type I error
  H0 is incorrect: and our analysis says less then 70 -->type II error

  how the null hypothesis can be accepted?
  null hypothesis tested under two bais
  1.parametric test: we compute mean,median and mode.
  z-test and t-test
  parametric test can be applied if my data is normally distributed

  2.non-parametric test: when the data is not normally distributed we use non-parametric test
  chi-square test

Q).in a classroom daily having absentes on monday 28, on tuesday 22,on wednesday 18, and thursday 20,friday 32.






**01-05-2025**

**13-05-2025**




**POWER BI**

**19-05-2025**

In [ ]:
#WHAT is list comprehension?
#it offeres smaller line of code where a new list is created from the existing list

In [ ]:
l = ['apple','banana','pineapple','kiwi','grapes','lemon','orange']
#print the fruits having letter 'a' in a new list?
new = []
for i in l:
  if "a" in i:
    new.append(i)
print(new)

['apple', 'banana', 'pineapple', 'grapes', 'orange']


In [ ]:
#new = [items for item in collections_name apply condition]
new = [i for i in l if "a" in i]
print(new)

['apple', 'banana', 'pineapple', 'grapes', 'orange']


In [ ]:
#print the even number in a new list up to 100
new = [i for i in range(0,101,2)]
print(new)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
#print all the letters in in upper format
new = [i.upper() for i in l]
print(new)

['APPLE', 'BANANA', 'PINEAPPLE', 'KIWI', 'GRAPES', 'LEMON', 'ORANGE']


**Lambda functions**

In [ ]:
#what is lambda?
#lambda means anonymous-->no name
#lambda() means a function it does not have any name

In [ ]:
#syntax:  lambda arguments: single_expression
#lambda is an anonymous function where it can takes many arguments and single expression

In [ ]:
a = lambda x: x+10
print(a(5))

15


In [ ]:
b = lambda x,y,z: x+y+z
print(b(10,20,30))

60


In [ ]:
#functiuons are 1st class objects means a function can act like argument to another function

In [ ]:
#lambda is more powerfull when you use inside the another function

In [ ]:
#creat a function to print power of 2,3,4 and sqrt
def square(n):
  return n**2
def cube(n):
  return n **3
def four(n):
  return n**4
def sqrt(n):
  return n**0.5
print(square(2))
print(cube(2))
print(four(2))
print(sqrt(4))

4
8
16
2.0


In [ ]:
#create same by using lambda
def power(n):
  return lambda x: x**n
square = power(2)
cube = power(3)
sqrt = power(0.5)

print(square(20))
print(cube(6))
print(sqrt(25))

400
216
5.0


**map()**

In [ ]:
#map() takes an function as an argument and run it over the each point in iterable

In [ ]:
fruits = ['apple','banana','pineapple','watermelon','kiwi','grapes']
#from the above print the length of each fruits in to new list
new = []
for i in fruits:
  new.append(len(i))
print(new)

[5, 6, 9, 10, 4, 6]


In [ ]:
lc = [len(i) for i in fruits]
print(lc)

[5, 6, 9, 10, 4, 6]


In [ ]:
m1 = set(map(len,fruits))
print(m1)
#Note:- before we are using map() we need to decide in what data type we need print the o/p-->list,tuple,set

{4, 5, 6, 9, 10}


In [ ]:
user = input().split()
m2 = list(map(int,user))
print(m2)

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
#print the l**2
m3 = list(map(lambda a: a**2,l))
print(m3)

**filter()**

In [ ]:
#synatx:- filter(function,iterables)
#filter function takes function as an argument and run it over each element in iterables and print only the element which are satisfied with filter()
age  = [18,13,14,16,20,22,13,24,67,43,32,36]
def check_age(n):
  if n>=18:
    return True
f = list(filter(check_age,age))
print(f)

In [ ]:
m = list(map(check_age,age))
print(m)

In [ ]:
f = list(filter(check_age,age))
print(f)

In [ ]:
f2 = list(filter(lambda a:a>=18,age))
print(f2)

**20-05-2025**

In [ ]:
#what is class?
#blue print of object
#what is an object?
#instence of a class is known as object

In [ ]:
#what are the four pillars of the oop's concept?
#1.polymorphism
#2.encapsulation
#3.inheretence
#4.abstraction

In [ ]:
# customer1 = ()
# 1.def def_welcome()
# 2.def check_balnce()
# 3.def deposit()
# 4.def withdraw()

In [ ]:
#How can we create a class?
class customer():
  #create class attributes
  Bank_Name = "HFC Bank"
  IFSC = "HFC0008762"
  Branch = "Ameerpet"
  city  = "HYD"
  State = "TS"

  #intialize the object attributes
  def __init__(self,Name,accno,intial_balance,phone):
    self.Name = Name
    self.accno = accno
    self.intial_balance = intial_balance
    self.phone = phone
  def welcome(self):
    print(f"Hello {self.Name} ! welcome to HFC Bank")
  def check_balance(self):
    print(f"Your current balace is {self.intial_balance}/- rupees only")
  def deposit(self,amount):
    self.intial_balance += amount
    print(f"""Transaction is completed.
    {amount} has been credited to your account.
    Updated balance is {self.intial_balance}""")
  def withdraw(self,amount):
    if amount<= self.intial_balance:
       self.intial_balance -= amount
       print(f"""Transaction is completed.
    {amount} has been credited to your account.
    Updated balance is {self.intial_balance}""")
    else:
      print('insufficient funds')
#create object
c1 = customer('shahul',532356243,10000,893932736)
#access the class attributes
c1.IFSC
c1.Branch
#access the object attributes
c1.accno
c1.intial_balance
#access the method
# c1.welcome()
# c1.check_balance()
# c1.deposit(25000)
c1.withdraw(7000)

Transaction is completed.
    7000 has been credited to your account.
    Updated balance is 3000


In [ ]:
#How many types of attributes do we have in python?
#There are 2 types
#1.class attribute:- sharable properties or data (common data)
#2.object attribute:- unique properties which shared with specific object

#How can we create an object attributes?
#before creating the object attributes we need initialize  the object attributes inside the class
#what is a method?
#method is a function created inside the class

In [ ]:
#create a login and registration page  where
#1.check the user is giving valid email or not
#2.password has to be more then 6 characters where it should have "special character, number, uppercase"
#3.use the file handling method to store all the user information
#4.if the user forget password--> retrive the password if the user email exist
#5.evaluation can be done checking registration,login, password pattern match, retrive password
#6.--> save the file in github and share link  --> readme, streamlit

**file handling**

In [ ]:
#what is file handling?
#handling a file except python--> pdf,json,xcel,csv...ect
#to handle this file in python we have an inbuilt function--> open()
#There are 4 modes in the file handling--> r,w,a,x

In [ ]:
#creat a file trail.txt by using python file handling
#exceution mode--> x-mode is ude to create afile
f = open('trail.txt','x')
print(f)

<_io.TextIOWrapper name='trail.txt' mode='x' encoding='utf-8'>


In [ ]:
#overwrite mode-->w-mode
f = open('trail.txt','w')
f.write('hello i am using file handling write mode')
f.close()

In [ ]:
#append a-mode
f = open('trail.txt','a')
f.write('.i am using append mode to add extra content')
f.close()

In [ ]:
#read mode- (r-mode)
#by default the open() is in read mode
f = open('trail.txt','r')
print(f.read())
f.close()

hello i am using file handling write mode.i am using append mode to add extra content


In [ ]:
#iterators
#pickling
#regular expresion
#handling the xcel file

**21-05-2025**

**regular expressions**

In [ ]:
#what is regular expression?
#aslo known as regex
#regex is sequence of characters that defines a search pattern
#used for string  searching, matching,replacing and validating.


In [ ]:
#import regular expression
import re
txt = "The rain in hyderabad"
#search "rain" is present in above string or not
print(re.search("rain",txt))

<re.Match object; span=(4, 8), match='rain'>


In [ ]:
#regex function:-
#1.findall():- returns the list containg all matches
#2.search():- returns the index position of 1st occurence
#3.split():- returns a list where the string has been split
#4.sub():- replace one or many matches

In [ ]:
#basic syntax of regex
"""1.dot(.)--> any character
   2.^-->start of string
   3.$--> end of the string
   4.*--> 0 or more repeating elements
   5.+--> 1 or more repeats
   6.?--> 0 or 1
   7.{n}--> exactly n times -->s{3}-->sss
   8.{n,}--> at least n times -->p{6,}
   9.{n,m}--> between the n and m times-->p{6,16}
   10.[]--> set of characters--->[a-z]"""

In [ ]:
#find all the numbers in a string
text = "the prices for mangos are 45,89,90,120 rupees"
#common patterns in regex--> \d--> digit[0-9]
num =re.findall(r'\d',text)
print(num)

['4', '5', '8', '9', '9', '0', '1', '2', '0']


In [ ]:
num =re.findall(r'\d+',text)
print(num)

['45', '89', '90', '120']


In [ ]:
#validate an email?
email = "nawinchandra03@gmail.com"
pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'--> #AI CODE
pattern = r'^[a-zA-Z0-9]+@[a-z]+\.[a-z]{2,}$' #common pattern -->\w+-->(a-z,A-Z,0-9)
if re.match(pattern,email):
  print("valid email")
else:
  print("invalid email")


valid email


In [ ]:
#extract the words having special characters-->
text = "i like #python and #AI"
hashtag = re.findall(r'#\w+',text)
print(hashtag)

['#python', '#AI']


In [ ]:
#replace the date format
# (dd/mm/yyyyy) --> (yyyy-mm-dd)
import re
text = "today is 21-05-2025"
new = re.sub(r'(\d{2})-(\d{2})-(\d{4})', r'\3-\2-\1',text)
print(new)

today is 2025-05-21


**Iterators**

In [ ]:
#what is iterators?
#iterators breaks large amount data into tiny chunks
l = ['apple','banana','watermelon','blueberry']
for i in l:
  print(i)

apple
banana
watermelon
blueberry


In [ ]:
#how this iterators can be built?
#iterators built based on two protocols
#1. _iter_
#2. _next_

In [ ]:
l = ['apple','banana','watermelon','blueberry']
i = iter(l)
print(next(i))

apple


**pickling**

In [ ]:
#what is pickling?
"""the process of converting 2D data into 1D and again converting 1D(.point data) data into 2D(---line data) data is known as pickling
#the process of serialization and deserialization is known as pickling
#we are converting the data in the form of bytes"""

In [ ]:
import pickle
data = {
    'name':'john',
    'age':'28',
    'city':'hyd'
}
with open("ex_pickle","wb") as file:   #wb means write binary
    pickle.dump(data,file) # This line needs to be indented
    print("the data has pickled and saved in ex_pickle") # This line also needs to be indented

the data has pickled and saved in ex_pickle


In [ ]:
#deserialization
with open('ex_pickle','rb') as file:
  load_data = pickle.load(file)
  print("the data has been deserialized")
  print(load_data)

the data has been deserialized
{'name': 'john', 'age': '28', 'city': 'hyd'}


In [ ]:
#my_sql_connector


**22-05-2025**